# Generated by Django 2.2 on 2020-09-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='referal_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
